openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:80'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
  /api/v1/register:
    post:
      summary: ''
      operationId: postApiV1Register
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: ''
                  example: deleniti
                last_name:
                  type: string
                  description: ''
                  example: repudiandae
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: pagac.jayce@example.net
                password:
                  type: string
                  description: ''
                  example: '`j@#BP#'
                password_confirmation:
                  type: string
                  description: ''
                  example: null
              required:
                - first_name
                - last_name
                - email
                - password
                - password_confirmation
      security: []
  /api/v1/login:
    post:
      summary: ''
      operationId: postApiV1Login
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: ytremblay@example.com
                password:
                  type: string
                  description: ''
                  example: 'jVe<uWD{6SwIpK4?Jfj'
              required:
                - email
                - password
      security: []
  /api/v1/users:
    get:
      summary: ''
      operationId: getApiV1Users
      description: ''
      parameters:
        -
          in: query
          name: page
          description: ''
          example: 1
          required: false
          schema:
            type: integer
            description: ''
            example: 1
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
  '/api/v1/messages/{chat_id}':
    get:
      summary: ''
      operationId: getApiV1MessagesChat_id
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: chat_id
        description: 'The ID of the chat.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/v1/message/{chat_id}':
    post:
      summary: ''
      operationId: postApiV1MessageChat_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: chat_id
        description: 'The ID of the chat.'
        example: 1
        required: true
        schema:
          type: integer
  /api/v1/chats:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters:
        -
          in: query
          name: page
          description: ''
          example: 1
          required: false
          schema:
            type: integer
            description: ''
            example: 1
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters:
        -
          in: query
          name: fromUser
          description: ''
          example: 10
          required: true
          schema:
            type: integer
            description: ''
            example: 10
        -
          in: query
          name: forUser
          description: ''
          example: 6
          required: true
          schema:
            type: integer
            description: ''
            example: 6
      responses: {  }
      tags:
        - Endpoints
  /api/broadcasting/auth:
    get:
      summary: 'Authenticate the request for channel access.'
      operationId: authenticateTheRequestForChannelAccess
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
