openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:80'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
  /api/v1/register:
    post:
      summary: ''
      operationId: postApiV1Register
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: ''
                  example: expedita
                last_name:
                  type: string
                  description: ''
                  example: facere
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: heidenreich.jermaine@example.org
                password:
                  type: string
                  description: ''
                  example: 'FrVu_2ub#S*.zq-xV'
                password_confirmation:
                  type: string
                  description: ''
                  example: null
              required:
                - first_name
                - last_name
                - email
                - password
                - password_confirmation
      security: []
  /api/v1/login:
    post:
      summary: ''
      operationId: postApiV1Login
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: griffin75@example.net
                password:
                  type: string
                  description: ''
                  example: "mZ8_2DDCz'W"
              required:
                - email
                - password
      security: []
  /api/v1/users:
    get:
      summary: ''
      operationId: getApiV1Users
      description: ''
      parameters:
        -
          in: query
          name: page
          description: ''
          example: 1
          required: false
          schema:
            type: integer
            description: ''
            example: 1
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
  /api/v1/messages:
    get:
      summary: ''
      operationId: getApiV1Messages
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 1
                    user_id: 133
                    text: test
                    created_at: '2024-07-19T15:13:23.000000Z'
                    updated_at: '2024-07-19T15:13:23.000000Z'
                    time: '19 Jul 2024, 15:13:23'
                    user:
                      id: 133
                      first_name: voluptatum
                      last_name: sed
                      email: forest92@example.org
                      email_verified_at: null
                      created_at: '2024-07-19T11:00:48.000000Z'
                      updated_at: '2024-07-19T11:00:48.000000Z'
      tags:
        - Endpoints
  /api/v1/message:
    post:
      summary: ''
      operationId: postApiV1Message
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
  /api/broadcasting/auth:
    get:
      summary: 'Authenticate the request for channel access.'
      operationId: authenticateTheRequestForChannelAccess
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
